[package]
name = "test-os"
version = "0.1.0"

[build-dependencies]
bootloader = "0.11.3"
test-kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }

[workspace]
members = ["kernel"]
